### ISSUE TITLE
Kinesis stream event mapping error - Module alias error: internal error: required and default are mutually exclusive for event_source

### ISSUE THREAD

**Issue by v135kuma** [pjodouin/ansible-lambda#11]
I am using Python 2.7 and Ansible 2.2.

As a task I am trying to Map Kinesis event stream to a lambda function. I am getting this error.

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Module alias error: internal error: required and default are mutually exclusive for event_source"}

Please, help me debug the issue.

  - name: create AWS Lambda Function
    lambda:
      name: "{{ ENV.router.lambda.name }}"
      description: "{{ ENV.router.lambda.description }}"
      aws_access_key: "{{ ENV.router.creds.accesskey }}"
      aws_secret_key: "{{ ENV.router.creds.secretkey }}"
      region: "{{ ENV.router.creds.region }}"
      zip_file: "{{ ENV.router.local.dest }}/{{ routerdir }}/{{ jar }}"
      runtime: "{{ ENV.router.lambda.runtime }}"
      timeout: "{{ ENV.router.lambda.timeout }}"
      handler: "{{ ENV.router.lambda.handler }}"
      memory_size: "{{ ENV.router.lambda.memory_size }}"
      role: "{{ ENV.router.lambda.role }}"

  - name: show results
    debug: var=lambda_facts

  - name: UAT alias for Lambda Function
    lambda_alias:
      function_name: "{{ ENV.router.lambda.name }}"
      name: UAT
      description: UAT
      state: present
      aws_access_key: "{{ ENV.router.creds.accesskey }}"
      aws_secret_key: "{{ ENV.router.creds.secretkey }}"

  - debug: msg="System {{ ENV.router.lambda.name }} has"

  - name: Kinesis stream event mapping
    lambda_event:
      function_name: "{{ ENV.router.lambda.name }}"
      state: present
      alias: UAT
      aws_access_key: "{{ ENV.router.creds.accesskey }}"
      aws_secret_key: "{{ ENV.router.creds.secretkey }}"
      source_params:
        source_arn: "{{ ENV.router.kinesis.arn }}"
        enabled: True
        batch_size: 500
        starting_position: TRIM_HORIZON

**Comment by pjodouin** [comment]
Hi, which ansible lambda module are you using, because I don't recognize the parameters?  Also, where exactly is this error occurring?  I can't see how "event_source" is related to the alias module.

**Comment by pjodouin** [comment]
Closing this issue as it does not pertain to these modules.  This issue most likely stems from the modules that have been included in the current "extras" distro and should thus be reported there.
