### ISSUE TITLE
How to update lambda code

### ISSUE THREAD

**Issue by plusseed** [pjodouin/ansible-lambda#4]
Hi,

I'm first deploy is successful.
and, lambda code update.
but, don't know update of the YAML.

now, update method is the transition 'present' from 'absent'.

```
    - name: List all for a specific function
      lambda_facts:
        query: versions
        function_name : "{{LAMBDA.NAME}}"
      register: is_exists
      ignore_errors: True

    - debug: var=is_exists

    - name: Delete Lambda Function
      lambda:
        state: absent
        type: code
        function_name: "{{LAMBDA.NAME}}"
      when: is_exists.failed is undefined

    - name: New Lambda Function
      lambda:
        state: present
        type: code
        function_name: "{{LAMBDA.NAME}}"
        runtime: "{{LAMBDA.RUNTIME}}"
        code:
          s3_bucket: "{{S3.BUCKET}}"
          s3_key: "{{S3.DEST}}"
        timeout: "{{LAMBDA.TIMEOUT}}"
        handler: "{{LAMBDA.HANDLER}}"
        role: "{{LAMBDA.ROLE}}"
        description: "{{LAMBDA.DESCRIPTION}}"
        vpc_config:
          subnet_ids: "{{ LAMBDA.SUBNET_IDS }}"
          security_group_ids: "{{ LAMBDA.SECURITY_GROUP_IDS }}"
        memory_size: "{{LAMBDA.MEMORY}}"
        starting_position: LATEST
        publish: True
```

> saw the botocore documentation.
> https://botocore.readthedocs.org/en/latest/reference/services/lambda.html#Lambda.Client.update_function_code

please, teach lambda code update of the YAML example.

**Comment by pjodouin** [comment]
Hi,

The modules are not yet idempotent as I was having issues similar to that with the API Gateway module.  I do plan on fixing this soon but until then, you can use "state=updated" to force an update to any of the lambda related resources, including code.

I am keeping this issue open as a motivator, thanks!

**Comment by plusseed** [comment]
Hi,

Thank you for your comment. 
I will using the previous YAML at until implemented.

**Comment by curras** [comment]
any update on this issue?

**Comment by pjodouin** [comment]
It's a little tricky due to the way the AWS API uses S3 to upload and
download lambda code.  I have a solution, which requires using a "local
path" to the deployment package.  I should have a working version of this
by end of this week.



On 23 February 2016 at 10:47, Sean Curran <notifications@github.com> wrote:

> any update on this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pjodouin/ansible-lambda/issues/4#issuecomment-187757150>
> .
>



-- 
Pierre Jodouin
Cloud Solutions Architect

**Comment by pjodouin** [comment]
Just committed a first stab at idempotent lambda called "ilambda".  I'll rename it when it's completed.  Code and config are now idempotent and supports check mode.

**Comment by pjodouin** [comment]
The lambda module is now idempotent.
**Note** that parameters have changed. Refer to `function.yaml` sample and html docs.

Will have _alias_ and _event_ modules done soon.
