### ISSUE TITLE
PR?

### ISSUE THREAD

**Issue by gamename** [pjodouin/ansible-lambda#6]
Hi Pierre,

Excellent work.  When do you plan to submit the PR?

**Comment by pjodouin** [comment]
Hi Tennis,

I'm still working on the idempotent version of the lambda module, which turns out to be a rewrite and tricky due to lambda versioning.  I should have it done before next week, at which time I will submit a PR.   

Thanks for the encouraging words!

**Comment by pjodouin** [comment]
PR submitted #1890
