### ISSUE TITLE
Question: Installation Folders

### ISSUE THREAD

**Issue by ranchodeluxe** [pjodouin/ansible-lambda#7]
I'd really like to try these ansible modules out but your installation instructions talk about a *custom modules folder* and *custom plugins folder*. Not sure where these are or how to configure them. I was hoping to find some information on these customizations on [Ansible's Developer] (http://docs.ansible.com/ansible/developing_plugins.html#vars-plugins) page. But I came up short.

Any chance you can point to the Ansible documentation that explains how to setup the paths to these custom folders or flesh out the installation directions a little bit more? I'd really appreciate it!

**Comment by viper233** [comment]
The custom directories will be relative to the directory where your playbooks are. ```./library``` is where you will store custom modules i.e. the .py files.
http://docs.ansible.com/ansible/developing_modules.html#developing-modules
http://docs.ansible.com/ansible/developing_plugins.html#distributing-plugins
Custom plugins will go in a directory relating to the plugin in type, e.g. a lookup plugin will got into ```./lookup_plugins```

**Comment by pjodouin** [comment]
Thanks for the question and thanks for answering it Stephen!
I've modified the REAME file to include these comments and links.

**Comment by ranchodeluxe** [comment]
thanks a ton @viper233 and @pjodouin!
