### ISSUE TITLE
Question: Creating Lambda Trust Policies

### ISSUE THREAD

**Issue by ranchodeluxe** [pjodouin/ansible-lambda#8]
I ran into a snag when I was trying to use these modules. None of my ansible-managed IAM roles can be created with a custom Trust Policy for aws.lambda ( [current ticket on this](https://github.com/ansible/ansible-modules-core/issues/2468) ). 

Just interested to know how you guys are setting these up in ansible? Manually? Proxying to the AWS CLI tool?

Thanks

**Comment by ranchodeluxe** [comment]
once possibility I guess is that you can just wrap the AWS CLI call with shell module
`local_action: shell aws iam create-role --role-name=<name> --assume-role-policy-document=file://devops/roles/iam_users/files/policies/lambda-s3-execution-trust-policy.json`

**Comment by pjodouin** [comment]
That's a good workaround.  I checked the current ansible code for IAM and
it doesn't allow for the inclusion of a trust policy as you've discovered.
I'll see if I can make a quick change to support this in the IAM module.

On 12 March 2016 at 14:47, sudobangbang <notifications@github.com> wrote:

> once possibility I guess is that you can just wrap the AWS CLI call with
> shell module
> local_action: shell aws iam create-role --role-name=<name>
> --assume-role-policy-document=file://devops/roles/iam_users/files/policies/lambda-s3-execution-trust-policy.json
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pjodouin/ansible-lambda/issues/8#issuecomment-195796173>
> .
>



-- 
Pierre Jodouin
Cloud Solutions Architect

**Comment by viper233** [comment]
ansible/ansible/pull/14633 I'm assuming you are facing assume role failures because of the issue relating to boto3 authentication. There aren't too many modules using boto3 yet, I had the same issue with the NAT Gateway modules.

**Comment by pjodouin** [comment]
Just made a quick patch to the IAM module and included it here (as a PR would probably take too long).
Put the module in the same ./library directory and it should override the core module.

```
  tasks:
  - name: Create IAM role with custom trust relationship
    iam:
      iam_type: role
      name: API2LambdaTestRole
      state: present
      trust_policy: iam_trust.json
```
Where _iam_trust.json_ can be something like this:
```

  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

**Comment by ranchodeluxe** [comment]
great work @pjodouin. really appreciate that. I'll give this a try later

**Comment by ranchodeluxe** [comment]
@pjodouin: works great!

**Comment by pjodouin** [comment]
@sudobangbang

Excellent!.  Not sure if you got the latest mods but I changed the
parameter names to allow for inline policies.  "trust_policy" is now a
JSON/YAML parameter and "trust_policy_filepath" is what the former
parameter used to be.

I submitted a PR to the ansible-modules-core repo this morning:
ansible/ansible-modules-core#3264
<https://github.com/ansible/ansible-modules-core/pull/3264>

On 16 March 2016 at 11:54, sudobangbang <notifications@github.com> wrote:

> @pjodouin <https://github.com/pjodouin>: works great!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pjodouin/ansible-lambda/issues/8#issuecomment-197393488>
>



-- 
Pierre Jodouin
Cloud Solutions Architect
